Training with a single process on 1 device (cuda:0).
WARNING: No pretrained configuration specified for MONet_T_4 model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
Model MONet_T_4 created, param count:3049362
Data processing configuration for current model + dataset:
	input_size: (3, 32, 32)
	interpolation: bicubic
	mean: (0.485, 0.456, 0.406)
	std: (0.229, 0.224, 0.225)
	crop_pct: 0.875
	crop_mode: center
AMP not enabled. Training in float32.
/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Scheduled epochs: 300. LR stepped per epoch.
Train: 0 [   0/625 (  0%)]  Loss: 2.30 (2.30)  Time: 1.572s,   40.71/s  (1.572s,   40.71/s)  LR: 1.000e-05  Data: 1.096 (1.096)
Train: 0 [  50/625 (  8%)]  Loss: 2.25 (2.29)  Time: 0.043s, 1488.68/s  (0.070s,  911.35/s)  LR: 1.000e-05  Data: 0.006 (0.026)
Train: 0 [ 100/625 ( 16%)]  Loss: 2.19 (2.26)  Time: 0.034s, 1859.01/s  (0.055s, 1159.97/s)  LR: 1.000e-05  Data: 0.001 (0.014)
Train: 0 [ 150/625 ( 24%)]  Loss: 2.17 (2.24)  Time: 0.036s, 1789.46/s  (0.050s, 1276.69/s)  LR: 1.000e-05  Data: 0.001 (0.010)
Train: 0 [ 200/625 ( 32%)]  Loss: 2.13 (2.23)  Time: 0.048s, 1336.49/s  (0.048s, 1337.07/s)  LR: 1.000e-05  Data: 0.001 (0.008)
Train: 0 [ 250/625 ( 40%)]  Loss: 2.18 (2.22)  Time: 0.035s, 1810.87/s  (0.047s, 1373.30/s)  LR: 1.000e-05  Data: 0.001 (0.007)
Train: 0 [ 300/625 ( 48%)]  Loss: 2.11 (2.21)  Time: 0.039s, 1637.53/s  (0.045s, 1406.99/s)  LR: 1.000e-05  Data: 0.001 (0.006)
Train: 0 [ 350/625 ( 56%)]  Loss: 2.17 (2.20)  Time: 0.041s, 1547.50/s  (0.045s, 1433.16/s)  LR: 1.000e-05  Data: 0.001 (0.005)
Train: 0 [ 400/625 ( 64%)]  Loss: 2.17 (2.20)  Time: 0.045s, 1429.27/s  (0.044s, 1453.02/s)  LR: 1.000e-05  Data: 0.001 (0.005)
Train: 0 [ 450/625 ( 72%)]  Loss: 2.22 (2.20)  Time: 0.051s, 1264.94/s  (0.044s, 1468.78/s)  LR: 1.000e-05  Data: 0.008 (0.004)
Train: 0 [ 500/625 ( 80%)]  Loss: 2.19 (2.19)  Time: 0.042s, 1514.92/s  (0.043s, 1479.66/s)  LR: 1.000e-05  Data: 0.001 (0.004)
Train: 0 [ 550/625 ( 88%)]  Loss: 2.30 (2.19)  Time: 0.043s, 1505.52/s  (0.043s, 1483.58/s)  LR: 1.000e-05  Data: 0.001 (0.004)
Train: 0 [ 600/625 ( 96%)]  Loss: 2.14 (2.19)  Time: 0.039s, 1641.63/s  (0.043s, 1491.67/s)  LR: 1.000e-05  Data: 0.001 (0.004)
Test: [   0/156]  Time: 1.017 (1.017)  Loss:   1.949 ( 1.949)  Acc@1:  34.375 ( 34.375)  Acc@5:  79.688 ( 79.688)
Test: [  50/156]  Time: 0.012 (0.032)  Loss:   2.019 ( 1.990)  Acc@1:  18.750 ( 28.983)  Acc@5:  82.812 ( 81.189)
Test: [ 100/156]  Time: 0.012 (0.022)  Loss:   1.879 ( 1.983)  Acc@1:  25.000 ( 28.759)  Acc@5:  85.938 ( 82.039)
Test: [ 150/156]  Time: 0.005 (0.019)  Loss:   2.003 ( 1.980)  Acc@1:  29.688 ( 29.450)  Acc@5:  82.812 ( 82.285)
Test: [ 156/156]  Time: 0.043 (0.019)  Loss:   2.022 ( 1.980)  Acc@1:  31.250 ( 29.490)  Acc@5:  81.250 ( 82.380)
Traceback (most recent call last):
  File "/home/sharipov/monet/train.py", line 1190, in <module>
    main()
  File "/home/sharipov/monet/train.py", line 900, in main
    weight_norms(model)
  File "/home/sharipov/monet/train.py", line 845, in weight_norms
    current_s_norm = spectral_norm(param.data)
  File "/home/sharipov/monet/train.py", line 837, in spectral_norm
    u, s, v = torch.svd(weight, compute_uv=False)
RuntimeError: linalg.svd: input should have at least 2 dimensions, but has 1 dimensions instead
[2024-04-13 19:00:25,532] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1471938) of binary: /home/sharipov/monet/venv/bin/python
Traceback (most recent call last):
  File "/home/sharipov/monet/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sharipov/monet/venv/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-13_19:00:25
  host      : i01.izar.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1471938)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
